### ISSUE TITLE
test no working

### ISSUE THREAD

**Issue by tetesh** [sampaiodiego/rocket.chat.load.tester#28]
Hello! Test no working. Please help   
Docker-compose logs:  
```
load-scale_1  | error during login {
load-scale_1  |   status: 401,
load-scale_1  |   data: { status: 'error', error: 'Unauthorized', message: 'Unauthorized' }
load-scale_1  | } {
load-scale_1  |   username: 'user.uid-21c0f6f74e3dce56c5074717c465c02c-8',
load-scale_1  |   password: 'performance',
load-scale_1  |   email: 'user.uid-21c0f6f74e3dce56c5074717c465c02c-8test-%s@test.ru'
load-scale_1  | }
load-scale_1  | Error during log in {
load-scale_1  |   status: 401,
load-scale_1  |   data: { status: 'error', error: 'Unauthorized', message: 'Unauthorized' }
load-scale_1  | }
load-scale_1  | Logged users total: 0
load-scale_1  | Starting sending messages
load-scale_1  | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getRandomSubscription' of undefined
load-scale_1  |     at /app/cjs/profile.js:184:43
load-scale_1  |     at step (/app/cjs/profile.js:48:23)
load-scale_1  |     at Object.next (/app/cjs/profile.js:29:53)
load-scale_1  |     at /app/cjs/profile.js:23:71
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at __awaiter (/app/cjs/profile.js:19:12)
load-scale_1  |     at /app/cjs/profile.js:178:42
load-scale_1  |     at /app/node_modules/@rocket.chat/emitter/dist/index.js:1:1003
load-scale_1  |     at Array.forEach (<anonymous>)
load-scale_1  |     at class_1.i.emit (/app/node_modules/@rocket.chat/emitter/dist/index.js:1:982)
load-scale_1  | (Use `node --trace-warnings ...` to show where the warning was created)
load-scale_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
load-scale_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
load-scale_1  | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getRandomSubscription' of undefined
load-scale_1  |     at /app/cjs/profile.js:227:35
load-scale_1  |     at step (/app/cjs/profile.js:48:23)
load-scale_1  |     at Object.next (/app/cjs/profile.js:29:53)
load-scale_1  |     at /app/cjs/profile.js:23:71
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at __awaiter (/app/cjs/profile.js:19:12)
load-scale_1  |     at /app/cjs/profile.js:223:52
load-scale_1  |     at /app/node_modules/@rocket.chat/emitter/dist/index.js:1:1003
load-scale_1  |     at Array.forEach (<anonymous>)
load-scale_1  |     at class_1.i.emit (/app/node_modules/@rocket.chat/emitter/dist/index.js:1:982)
load-scale_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
load scale environment:
```
    environment:
      - HOST_URL=http://127.0.0.1:3000
      - HOW_MANY_USERS=${HOW_MANY_USERS:-10}
      - USERS_PER_ROOM=${SEATS_PER_ROOM:-5}
      - LOGIN_BATCH=${LOGIN_BATCH:-5}
      - SSL_ENABLED=${SSL_ENABLED:-no}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - TASK_ID=1
      - CLIENT_TYPE=web
      - USERS_USERNAME=test-%s
      - USERS_PASSWORD=test-%s
      - USERS_EMAIL=test-%s@test.ru
```
Errors are repeated, new users do not appear in rocket chat

**Comment by tetesh** [comment]
in logs rocket-chat i see:
```
{"level":40,"time":"2022-07-12T17:40:00.081Z","pid":1,"hostname":"92f1532ec69b","name":"API","msg":"attribute query is deprecated"} 
```
