### ISSUE TITLE
error during login TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by TBG-FR** [sampaiodiego/rocket.chat.load.tester#7]
Hello there !

I'm trying to use that project, but when I do `docker-compose up` I get this error...
I tried to find which piece of code could be responsible for this error, but for now I'm stuck

Any idea ? Already seen that error ?
Maybe [this comment](https://github.com/node-fetch/node-fetch/issues/481#issuecomment-403595704) could lead to something ?

```
load-scale_1  | 2020-09-18T13:40:29.779Z app:server Listening on port 3000
load-scale_1  | connecting clients: 1
load-scale_1  | logging in clients: 1
load-scale_1  | [ '[API] POST error(login): {}' ]
load-scale_1  | error during login TypeError: Only absolute URLs are supported
load-scale_1  |     at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
load-scale_1  |     at /app/node_modules/node-fetch/lib/index.js:1410:19
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
load-scale_1  |     at Client.post (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:32:16)
load-scale_1  |     at RocketChatClient.<anonymous> (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:102:52)
load-scale_1  |     at Generator.next (<anonymous>)
load-scale_1  |     at /app/node_modules/@rocket.chat/sdk/lib/api/api.js:7:71
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at __awaiter (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:3:12)
load-scale_1  | error TypeError: Only absolute URLs are supported
load-scale_1  |     at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
load-scale_1  |     at /app/node_modules/node-fetch/lib/index.js:1410:19
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
load-scale_1  |     at Client.post (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:32:16)
load-scale_1  |     at RocketChatClient.<anonymous> (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:102:52)
load-scale_1  |     at Generator.next (<anonymous>)
load-scale_1  |     at /app/node_modules/@rocket.chat/sdk/lib/api/api.js:7:71
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at __awaiter (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:3:12)
load-scale_1  | [ '[API] POST error(users.register): {}' ]
load-scale_1  | error register TypeError: Only absolute URLs are supported
load-scale_1  |     at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
load-scale_1  |     at /app/node_modules/node-fetch/lib/index.js:1410:19
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
load-scale_1  |     at Client.post (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:32:16)
load-scale_1  |     at RocketChatClient.<anonymous> (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:102:52)
load-scale_1  |     at Generator.next (<anonymous>)
load-scale_1  |     at /app/node_modules/@rocket.chat/sdk/lib/api/api.js:7:71
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at __awaiter (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:3:12)
load-scale_1  | [ '[API] POST error(login): {}' ]
load-scale_1  | error during login TypeError: Only absolute URLs are supported
load-scale_1  |     at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
load-scale_1  |     at /app/node_modules/node-fetch/lib/index.js:1410:19
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
load-scale_1  |     at Client.post (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:32:16)
load-scale_1  |     at RocketChatClient.<anonymous> (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:102:52)
load-scale_1  |     at Generator.next (<anonymous>)
load-scale_1  |     at /app/node_modules/@rocket.chat/sdk/lib/api/api.js:7:71
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at __awaiter (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:3:12)
load-scale_1  | could not login/register for { username: 'test.user.3',
load-scale_1  |   password: 'test.pwd.3',
load-scale_1  |   email: 'tester-3@domain.com' } TypeError: Only absolute URLs are supported
load-scale_1  |     at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
load-scale_1  |     at /app/node_modules/node-fetch/lib/index.js:1410:19
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
load-scale_1  |     at Client.post (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:32:16)
load-scale_1  |     at RocketChatClient.<anonymous> (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:102:52)
load-scale_1  |     at Generator.next (<anonymous>)
load-scale_1  |     at /app/node_modules/@rocket.chat/sdk/lib/api/api.js:7:71
load-scale_1  |     at new Promise (<anonymous>)
load-scale_1  |     at __awaiter (/app/node_modules/@rocket.chat/sdk/lib/api/api.js:3:12)
load-scale_1  | opening rooms
load-scale_1  | sending messages
load-scale_1  | done!
```

System information:
- Rocket.Chat Server under `3.6.1` (also tried with `3.5.4`
- Operating System: Debian (on WSL)
- Deployment Method : `docker-compose`

Config:
```
# this is my container with RocketChat, it is in the "load-scale" network and reachable
      - HOST_URL=rocketchat_ubu_dev_1:3000
# other params
      - SEATS_PER_ROOM=15
      - ROOM_ID=loadtester
      - REDIS_HOST=redis
      - SSL_ENABLED=no
      - USERS_USERNAME=test.user.%s
      - USERS_PASSWORD=test.pwd.%s
      - CLIENT_TYPE=web
```

**Comment by TBG-FR** [comment]
Resolved by replacing `HOST_URL` value `rocketchat_ubu_dev_1:3000` with `http://rocketchat_ubu_dev_1:3000`
If you're using an IP address (eg: `172.17.0.4:3000`) you must do the same : `http://172.17.0.4:3000`

This also resolves the following error:  
`could not login/register for [...] TypeError: Only HTTP(S) protocols are supported`
